### ISSUE TITLE
load  pipeline problem: unet/mvdiffusion.models_unclip.unet_mv2d_condition.py not exist

### ISSUE THREAD

**Issue by ggxxii** [pengHTYX/PSHuman#11]
Hi, 

Great work！

I've been running inference.py, and encounter this error, anything i need to adjust?

ValueError: unet/mvdiffusion.models_unclip.unet_mv2d_condition.py as defined in `model_index.json` does not exist in pengHTYX/PSHuman_Unclip_768_6views and is not a module in 'diffusers/pipelines'.

Are there some files missing?

**Comment by Jack171516** [comment]
Hi, have you solved the problem yet?

**Comment by pananananas** [comment]
I also tried, but didn't manage to solve it

**Comment by pengHTYX** [comment]
> Hi,
> 
> Great work！
> 
> I've been running inference.py, and encounter this error, anything i need to adjust?
> 
> ValueError: unet/mvdiffusion.models_unclip.unet_mv2d_condition.py as defined in `model_index.json` does not exist in pengHTYX/PSHuman_Unclip_768_6views and is not a module in 'diffusers/pipelines'.
> 
> Are there some files missing?

Hi, could you please post more error log? Or I think you can download the pretrained weights from huggingface by yourself and specify the ```pretrained_model_name_or_path```  as the local path during inference. I hope this helps.

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/40406153-61df-47dc-8d71-7adc9454aedf)
pengHTYX/PSHuman_Unclip_768_6views  ' s model_index.json ,Unet moudle is \ mvdiffusion.models_unclip.unet_mv2d_condition'
when load diffusers 
![image](https://github.com/user-attachments/assets/979443a0-bbed-4b49-8f97-6e3080154570)

**Comment by ggxxii** [comment]
> > Hi,
> > Great work！
> > I've been running inference.py, and encounter this error, anything i need to adjust?
> > ValueError: unet/mvdiffusion.models_unclip.unet_mv2d_condition.py as defined in `model_index.json` does not exist in pengHTYX/PSHuman_Unclip_768_6views and is not a module in 'diffusers/pipelines'.
> > Are there some files missing?
> 
> Hi, could you please post more error log? Or I think you can download the pretrained weights from huggingface by yourself and specify the `pretrained_model_name_or_path` as the local path during inference. I hope this helps.

Yeah! I managed to make it work by manually downloading and putting the weights into corresponding folders.

**Comment by bro-chj** [comment]
> > > Hi,
> > > Great work！
> > > I've been running inference.py, and encounter this error, anything i need to adjust?
> > > ValueError: unet/mvdiffusion.models_unclip.unet_mv2d_condition.py as defined in `model_index.json` does not exist in pengHTYX/PSHuman_Unclip_768_6views and is not a module in 'diffusers/pipelines'.
> > > Are there some files missing?
> > 
> > 
> > Hi, could you please post more error log? Or I think you can download the pretrained weights from huggingface by yourself and specify the `pretrained_model_name_or_path` as the local path during inference. I hope this helps.
> 
> Yeah! I managed to make it work by manually downloading and putting the weights into corresponding folders.

hello, I encountered the same problem, and I have download the pretrained weights but I don't know how to place it, and how to specify the `pretrained_model_name_or_path`, could you help me
