### ISSUE TITLE
Inconsistent experimental results with the SIFu paper

### ISSUE THREAD

**Issue by zjh21** [pengHTYX/PSHuman#2]
Thank you for your great work! I have a question about the experimental results on CAPE. 
As the SIFu paper https://arxiv.org/abs/2312.06704 reports, its performance on the CAPE dataset is 0.7725 Chamfer and 0.7354 P2S on CAPE-NFP, 0.6297 Chamfer and 0.5980 P2S on CAPE-FP. 
However, in your paper, the scores of SIFu are 1.5742 Chamfer and 1.2777 P2S on CAPE-NFP, 1.0535 Chamfer and 0.9674 P2S on CAPE-FP. The scores are obviously different.
I notice that SIFu was trained on THuman2.0, not THuman2.1 + CustomHumans, which suffers from smaller dataset scale. Nevertheless, its reported scores are higher.
Did you retrain SIFu and other methods on THuman2.1 + CustomHumans? Or did you test their open-source weights with different settings?

**Comment by pengHTYX** [comment]
> Thank you for your great work! I have a question about the experimental results on CAPE. As the SIFu paper https://arxiv.org/abs/2312.06704 reports, its performance on the CAPE dataset is 0.7725 Chamfer and 0.7354 P2S on CAPE-NFP, 0.6297 Chamfer and 0.5980 P2S on CAPE-FP. However, in your paper, the scores of SIFu are 1.5742 Chamfer and 1.2777 P2S on CAPE-NFP, 1.0535 Chamfer and 0.9674 P2S on CAPE-FP. The scores are different. I noticed that SIFu was trained on THuman2.0, not THuman2.1 + CustomHumans, which suffers from a smaller dataset scale. Nevertheless, its reported scores are higher. Did you retrain SIFu and other methods on THuman2.1 + CustomHumans? Or did you test their open-source weights with different settings?

Hi, sorry for the delayed reply. We use the ECON settings for all evaluations. Due to the lack of evaluation details for SIFU, we perform comparisons with the same setting. I believe the errors may stem from various factors, including the alignment process with the ground truth scans.

**Comment by zjh21** [comment]
Thank you for your reply.
