### ISSUE TITLE
Minimum VRAM (CUDA out of memory)

### ISSUE THREAD

**Issue by zjh21** [pengHTYX/PSHuman#4]
Thank you for releasing the code and I tried it immediately. I managed to get the code running by downloading the pretrained weights. Otherwise, if the code tries to load from huggingface, it cannot find ```mvdiffusion.models_unclip.unet_mv2d_condition.```

The next problem that I encounter is CUDA OOM. I am using a NVIDIA GeForce RTX 4090 GPU with 24G VRAM. First, it reports OOM at ```"diffusers/models/autoencoders/autoencoder_kl.py", line 260, in encode: h = self.encoder(x). ```After setting PYTORCH_CUDA_ALLOC_CONF to a smaller number, such as  ```PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512```, the code can proceed to  ```"diffusers/models/autoencoders/autoencoder_kl.py", line 275, in _decode: dec = self.decoder(z). ``` With error:

```torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.88 GiB. GPU 0 has a total capacty of 23.63 GiB of which 4.48 GiB is free. Process 2188 has 390.70 MiB memory in use. Including non-PyTorch memory, this process has 17.27 GiB memory in use. Of the allocated memory 16.37 GiB is allocated by PyTorch, and 149.60 MiB is reserved by PyTorch but unallocated. ```

This time the memory gap is obviously large: 7.88GB vs. 4.48GB. Therefore, I need to ask what is the minimum VRAM required for PSHuman. Thank you very much for your assistance.

**Comment by pengHTYX** [comment]
The current model is trained at a resolution of 768, requiring over 40GB of VRAM. We are considering training a new model at a resolution of 512, which would allow it to run on an RTX 4090.

**Comment by zjh21** [comment]
Thank you. I managed to get the code working on a A6000.

**Comment by amberhappy** [comment]
Hi！if there are new model at resolution of 512 available?
